### ISSUE TITLE
Error while building the sample for ios

### ISSUE THREAD

**Issue by solewalker** [openfl/extension-iap#18]
I an getting this error while building the sample for ios 
``../../../../src/ui/Store.hx:371: characters 92-108 : String should be Null<Float>
../../../../src/ui/Store.hx:371: characters 92-108 : String should be Float
make: *** [build-haxe-i386] Error 1``

Its triggered particularly for this ``price: fastEl.att.price``

**Comment by TBaudon** [comment]
use Std.parseFloat
