### ISSUE TITLE
initilization fails on android

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [openfl/extension-iap#26]
Initilization fails for me on android because the parameter to onStarted is null.

If I change its type to "Dynamic", it works.

I believe there are a few other functions, for which it is the same case.

**Comment by fbricker** [comment]
Hi, we've just fixed this -and many other issues that came together with haxe 3.2 upgrade.
It's not on haxelib yet, so you should use the github version for now.

Thanks for reporting :)
